### PR TITLE
Search for static websites

### PR DESCRIPTION
**Pull request by onigoetz**

### CODE REVIEW

**Comment by onigoetz** [comment]
@djohnanderson Thank you very much for your work, I changed a few things, but it was already great work :D

**Comment by djohnanderson** [comment]
Glad to hear that you were able to use it. This was my first php project. I’m curious to know what improvements you made?

**Comment by onigoetz** [comment]
Sure, 
I didn't change much actually. the list looks big, but they're mainly cosmetic changes.

It's in two commits : 
- 55ef0b982bb9e334ba2445a8d23c44acfdf2f0b7:
  - I added a method (`getPureContent`) that will return just the content and not the template, the problem was that if I'm searching for, let's say "Getting Started" in the default documentation, it would return all pages as the text i'm looking for is in the navigation panel.
- d4c78ae3f9ca0c4899fc1def7d1f5b9b3cbe9d88:
  - Added a short documentation page
  - renamed the `text_search` parameter to `search` and placed it inside `html` as it is only available in html rendering.
  - write the `tipuesearch_content.json` directly in the generated files, so we don't need to add it to `.gitignore`
  - Added a bit of styling to the form field + a search icon. (looks like I changed all the css, but it's just my IDE's automatic formatting)
  - Added a white background to search results.
  - Removed the non-compressed `tipuesearch.js` and used the already included `tipuesearch.min.js`

Three other things : (only one is about PHP)

Instead of 
  ```php
array_push($index_pages, ['title' => $node->getTitle(), ... ]);
```
You can use this
  ```php
$index_pages[] = ['title' => $node->getTitle(), ... ]
```
Using the empty `[]` means "create a new entry"

Adding `style="display:none"` to `<div class="doc_content">` Actually hides all the content to recent search engines, so that's not good for indexing. I tried and it works to not add it at all, Tipue will hide it if it has to show search results.

Last one, using a `<p>` to add a search input will lead to weird results. Generally, `<p>`'s have a bottom margin and adding this in a place like the title bar leads to spacing issues, it's recommended to use a `<form>` or a `<div>` in this case because they don't have a margin/padding by default.

**Comment by djohnanderson** [comment]
Thanks for the nice improvements — and for explaining them!


> On Mar 14, 2016, at 2:43 PM, Stéphane Goetz <notifications@github.com> wrote:
> 
> Sure, 
> I didn't change much actually. the list looks big, but they're mainly cosmetic changes.
> 
> It's in two commits :
> 
> 55ef0b9 <https://github.com/justinwalsh/daux.io/commit/55ef0b982bb9e334ba2445a8d23c44acfdf2f0b7>:
> I added a method (getPureContent) that will return just the content and not the template, the problem was that if I'm searching for, let's say "Getting Started" in the default documentation, it would return all pages as the text i'm looking for is in the navigation panel.
> d4c78ae <https://github.com/justinwalsh/daux.io/commit/d4c78ae3f9ca0c4899fc1def7d1f5b9b3cbe9d88>:
> Added a short documentation page
Much nicer to put text_search inside html
> renamed the text_search parameter to search and placed it inside html as it is only available in html rendering.
> write the tipuesearch_content.json directly in the generated files, so we don't need to add it to .gitignore
> Added a bit of styling to the form field + a search icon. (looks like I changed all the css, but it's just my IDE's automatic formatting)
> Added a white background to search results.
> Removed the non-compressed tipuesearch.js and used the already included tipuesearch.min.js
> Three other things : (only one is about PHP)
> 
> Instead of
> 
Nice tip:
> array_push($index_pages, ['title' => $node->getTitle(), ... ]);
> You can use this
> 
> $index_pages[] = ['title' => $node->getTitle(), ... ]
> Using the empty [] means "create a new entry”
> 
I had intended to remove display:none, which was left over from a previous iteration, thanks for catching it.

**Pull request merged**
