### PR TITLE
Big reorganisation

### PR DESCRIPTION
**Pull request by onigoetz**
Hi,

I know this is a big pull request, but I needed all these functionnalities at the same time and could not make a lot of small pull requests. I will explain what I did in details here.

## General
- PSR-2 Coding style is now PSR-2, this eases the collaboration between projects
- PHP 5.4 is a minimum, it makes the code more readable in some places. and PHP 5.3 is unsupported for a long time now

## Code Structure
- Uses PSR-4 Standard, easier autoloading.
- Separated "Generator" and "Server" make a much clearer code.
- Also separated "Tree" to generate the structure.

## Features
- Abstract generation system, be able to choose how to generate the documentation
- Added Atlassian Confluence upload support (with image attachments and code highlight)
- Replaced Parsedown by CommonMark
- Added internal links
- Extend Daux with "Processors" a class to change the tree and generate new pages on the fly
- The project is packaged as `phar` archive. allowing to run easily without requiring dozens of files. easy to commit with the documented project.

## Documentation structure
- Images are now directly in the docs folder, make a more contained documentation : generator/server on one side, documentation on the other
- `resources` folder contains `js` files, `themes` and `img`. makes it easier to configure the copy on generation.

## Templates
- Templates are now generated with http://platesphp.com/
- Templates are much cleaner and overridable by creating a `templates` folder inside the theme and naming the template the same way as the original one. the engine does the rest.

## Bugfixes
- in generated mode, the name of the documentation links to `index` instead of `index.html`
- if there are no links, the documentation doesn't show the "show/hide code blocks" toggle
- a _index.md page in a sub folder now uses the default template and not the one for homepages.
- Page.md is exactly the same as Page/_index.md, the index Page calculation takes it in account.

Don't hesitate if you want me to fix/change something before you accept the pull request.

### CODE REVIEW

**Comment by holodyn** [comment]
Excellent pr - this corrected the issues we had previously patched and more.  You did remove however the ability to override a template without modifying the core files.  What would be a good place to have template override files? I'm thinking they can be packaged with a resources/themes/ folder.

**Comment by lossendae** [comment]
This looks, I hope it get merged soon, and, in the meantime why not switch to CommonMark ?

**Comment by onigoetz** [comment]
Migrating to commonmark was one of my ideas also, but this is already a huge pull request and I wanted it merged in before I go further in my customisations.

I have also other ideas that I already explore in other branches in my fork like being able to export in multiple different formats. My first planned alternative is exporting to atlassian's confluence, but after that why not also do ebooks or pdf or anything like that?

**Comment by lossendae** [comment]
I switched to Commonmark, it was fairly simple (3 changes, the instanciation, the method call and the class import).
In the other hand, even with your modification, it's impossible to switch to another highlighting library easily, there are still too much hard coded assets. But it's quite a good start.
This repository is not very active, I may have to directly fork your contribution.

**Comment by holodyn** [comment]
Added an abstraction layer in pull request #265, added CommonMark package, and set CommonMark as the demo option.

Should solve this moving forward.

**Comment by lossendae** [comment]
Super nice. 

It's better than just replacing the default parser knowing that CommonMark does not support some important github flavored markdown (mainly tables).

**Comment by onigoetz** [comment]
Heys guys, just a quick heads up, are you interested in my changes ?

If not I will remove my pull request and rename the project. (with all due references to the original work)

I have a lot of things I still want to contribute, but I don't want to contribute to a project that isn't supported.

**Comment by justinwalsh** [comment]
@onigoetz This looks amazing! I just checked out the latest version of this PR, and it looks like things are working nicely except the landing page images look to be broken links now. Once those are fixed, I think this is ready to merge.

Would you be interested in joining the project as a core contributor? We could use the help getting this project back in order. :) There are a lot of outstanding PRs and issues. Just let me know and I would be happy to add you to the project. You would be able to contribute whenever and on whatever you saw fit.

I know @dkisselev and @Gautham would love to have you on the core team.

**Comment by onigoetz** [comment]
For the error, it's an easy one, I just pushed a fix, we don't have the same workflow, I don't use Grunt to run the embedded web server
Because of the images served by php, we need to define the router when starting the server.

I would be very happy to join the core team :)
I can't guarantee a lot of time on the project as I have other projects going on but for the next weeks I will work a lot on documentations and will find new bugs / features to add

**Comment by onigoetz** [comment]
Oh Btw, as there are really a lot of changes and I forgot to specify it in the big changelog at the top of the page.
I removed the text editor.

The way I see it, the main feature is documentation generation in different formats, being able to watch your changes live is a plus, but it's a side feature.

Plus there are a lot of nice markdown editors out there.

I hope we're on the same page.

**Comment by justinwalsh** [comment]
I have added you as a contributor :) Thanks for your willingness to help!

I think we are on the same page regarding the editor. Was the reason for removing it just to simplify the refactor? If so it's possible someone might come along and add it again someday under the new coding standards.

A quick note about the project setup since you are now on the team. All commits to master will auto-deploy from my continuous integration server to daux.io. If you want to build in a staging environment, we have a development branch that is way behind master that could be brought back to life. Let me know if you have any questions. Otherwise feel free to clean up any old PRs or issues that you would like.

And go ahead and merge this PR when you are ready :)

**Comment by onigoetz** [comment]
Nice, thanks :D

Yes, I removed the editor during the refactoring of the tree. It simplified a few things.

Okay no problem for the integration and deployment. I had the idea that one of the generators could be a static jekyll site, would you find that interesting ? With this the website could be hosted on github and remove the fear of breaking it when we push to master.


I will merge the branch tomorrow morning (I live in switzerland, here it is the middle of the night)

Apart from the integration system, is there anything I should know? Is there a  communication process or something like that between team members?

**Comment by dkisselev** [comment]
When Gautham and I were working on Daux we shot emails back and forth for help and to co-ordinate who was working on what. Feel free to email either of us (and/or Justin) if you need a hand, but as you can tell, we've been too busy to actively work on Daux in the last few months.

**Comment by onigoetz** [comment]
@dkisselev Okay, I will use Git flow for my development. workflow.

I don't like to see projects as competing, I have a more "best tool for the job" philosophy. If it is more convenient for the user to edit and create a template with daux but he wants to deploy it on github.io for hosting reasons, and also create a PDF/ Epub from his documentation, with Daux he would be able to do it, but not with jekyll.

But okay, If you don't see it a good idea, I will not do it ;-)

**Pull request merged**
