### PR TITLE
Fix for files with cyrillic and chinese names

### PR DESCRIPTION
**Pull request by aleshkanet**
Fix for files with Cyrillic names

### CODE REVIEW

**Comment by aleshkanet** [comment]
also tested chinese named files, it's work fine.

**Comment by onigoetz** [comment]
Can you please check if the problem is the same with the latest development branch and if yes can you please create a new pull request for it ?

**Comment by onigoetz** [comment]
I made a quick check and added files with chinese and cyrillic characters, it seems to work correctly, can you check on your side ?

**Comment by aleshkanet** [comment]
my internal server encoding is different from utf8 (as in code ISO-8859-1) and I can't change the php.ini so I have to manually convert some strings in your code(it's not good way). I have another solution, but I can't test at this time.
e.g.
.htaccess
AddDefaultCharset UTF-8
php_value default_charset UTF-8

**Comment by onigoetz** [comment]
Hi, 

we added support for metadata in markdown files, by default you can override the title of a page with that:

```markdown
title: How to use markdown_metadata
-----
Hi, I'm the content
```

This is the recommended way if your configuration doesn't support UTF-8

**Pull request closed without merging**
