### PR TITLE
using daux.io like a library

### PR DESCRIPTION
**Pull request by stefanorg**
Hi i'm writing a module for zendframework 2 to integrate daux.io like a library inside my project.

I've done:
 *  some refactoring with OOP style
 *  refactored composer with psr-0 autoloadin
 *  added a setter in Daux.php to be able to overwrite the $docBase path
 *  added a init_autoloader.php file to remove the require in Daux.php class and do autoloading in index.php and generate.php script.
 *  removed the vendor folder cause no one need, you just need to do 'composer.phar install'

Cheers

### CODE REVIEW

**Comment by dkisselev** [comment]
Hey Stefan, I'm really sorry that I haven't gotten back to you. I've been really busy and have had no time at all to maintain daux, so at this point it's falling into semi-unmaintained status.

I still fully intend to merge your changes in, they look great and I'm grateful for the awesome work you put in, I just want to find a chance to clone and test everything first because the changes are relatively major (but I've been unable to put any time at all into daux in the past few months).

**Comment by stefanorg** [comment]
:+1:

**Comment by onigoetz** [comment]
Hi Stefan,

We're about to merge a big refactoring that also adds proper autoloading, can you check if it works for you ?

It is located in the develop branch for the moment.

**Comment by onigoetz** [comment]
I close this pull request as it is not mergeable at the moment, we're close to having daux working as a packagist dependency.

Follow #131 if you want news on this feature

**Pull request closed without merging**
