### PR TITLE
Patch / Sort update

### PR DESCRIPTION
**Pull request by holodyn**
Patch to temporarily correct unassigned "entry_page" value when a sub-folder only contains a single index.

Preliminary sort on build tree to improve first_page identification.

Need testing on "View Documentation" assignment when only nested index pages are available.  Currently fails with invalid URI.

### CODE REVIEW

**Comment by holodyn** [comment]
Patched daux_page uri usage for View Documentation error.

**Comment by holodyn** [comment]
## Site index identification

- Patched "first_page" usage to use the _index.md for the initial request, or index.md file if available.
- Modified the navbar header to render a base url link only.

## LOCAL_BASE constant

- Added constant definition to the entry pages index.php & generate.php to be used for the $daux->local_base value when initialized.  This is necessary to allow symlink packages to work properly.

## Index title identification

- Altered the method for which the document title for index pages is identified, using instead the containing folder name when available.  This prevents the word "index" from being used as the document title.

## Image / Raw file downloads

- Removed the extension definitions from the .htaccess RewriteRule to correct a 404 header error (primarily affecting Chrome)
- Added Content-length to the headers generated in the RawPage output

## config.json within tree

- Added loading of config.json files during the tree traversing / building procedure.  Custom configuration params are used for that node and descendants only.

## Added ipfilter config array

- Filter incoming requests from accessing a folder by IP address.  Useful during the document authoring process.

## Added inherit_index config flag

- Disabled by default, the inherit_index flag alters the lookup procedure for the index page of a folder.   When enabled, each folder will inherit the first available index or page of a descendant node in the folder tree.  This does not change the existing usage of the index files available but allows folders that do not contain an index file to inherit the first available Content item as the index.

**Comment by holodyn** [comment]
# Markdown Parser abstraction
- Added MarkdownParser abstraction layer.
- Added \League\CommonMark to vendor tree.
- Created two parser handlers, Parsedown and CommonMark
- Assigned Parsedown as default, CommonMark as active in example docs.

**Comment by onigoetz** [comment]
Hi,
All these should be fixed and be in the development branch.

If you want to re-propose your markdown parser abstraction, can you create a new pull request please?

**Comment by holodyn** [comment]
Yes - I'll do that now

**Comment by holodyn** [comment]
@onigoetz - since we forked your refactor two months ago you have refactored the tree again.  This merge will take a bit more time unfortunately.  I'll submit the PR as soon as possible.

**Comment by holodyn** [comment]
@onigoetz - hey bud I've just reviewed your restructuring and need to make sure I understand your logic before trying to refactor my parser solution into this new codebase.

As I understand it, your logic / convention is thus that the rendering of a page is passed through the following:  Processor -> Generator -> Formatter -> Converter

Does this sound correct?  The Generator / Formatter / Converter layers seem a bit mixed together so I want to make sure I have a clear picture before this is refactored for the parser changes.

Also you have the hack for the "processor_instance" that I would like to address, since as you mentioned in the comments it isn't very pretty.  Along with that it would be nice to to refactor the "extendCommonMarkEnvironment" logic since that specific convention should probably not be held in the processor, unless we want to be adding extension function for every parser in the future.

Thank in advance.  We can Skype if you prefer.

**Comment by onigoetz** [comment]
It's not exactly that.

The process goes like this : Create the tree -> Iterate on the tree to generate the files

The markdown conversion is done in the second step and is tied to the generator.

The Processor can hook on any step, for the moment it is : tree creation, generator initialization, markdown extension

If you have an idea to provide the processor_instance differently, I would be interested.

Yes we might want to provide other extension means, but the only way to extend the markdown parser is to extend that "Environment" class, and that can only be done at this particular step where I did it.

**Comment by holodyn** [comment]
Gotcha.  Thank you.  I understand the tree / iterator logic, but once the processor / generator are introduced for rendering we've got several layers here that I think can be compressed to make for easier expansion / interpretation moving forward.  Some of the class logic in place seems to be a direct result of the Confluence generator needs and could possibly stay compartmentalized within that sub-package.

We also have two separate "Generator" terms being used here, which is a bit confusing.  Maybe they could be collapsed or named differently.  It seems like we are hardly using the Application, Command, or Helper classes in the libs/generator folder.  Maybe we can just trash those altogether.

I believe there are several ways we can tackle this problem that should give us the same environment control while reducing the complexity of this processor / generator / formatter / handler logic currently in place.

Maybe something like this:
Environment -> Server -> Application -> Processor -> Builder (Tree) -> Generator -> Parser

Environment callbacks could be triggered from any subsequent layer.

Thanks again for the feedback.  I can't work on this today but I'll make some headway over the next few days.

**Comment by onigoetz** [comment]
I'm not sure to follow you ? what are the 2 different terms for generator ?

No we can't trash `Application` and `Command` together, as we're implementing symfony/console and both classes are needed. And later we might add other commands.

If you can reduce the complexity of the generators I would be happy to see it, but I'm not sure that what you propose will really be easier

**Comment by holodyn** [comment]
The term Generator is being used to namespace the Application and Command classes.  The term is also being used to describe the Formats, as in "getGenerators".  I think one of these should be removed as a concept or renamed.

**Comment by onigoetz** [comment]
I renamed the namespace for the command, now it is `Console`. Is it any clearer ?

**Comment by holodyn** [comment]
Yeah that works

**Comment by onigoetz** [comment]
Hi, just dropping a line to say I updated the generation part to separate Mardown from the generation process.

Now there is a `ContentType` interface, which permits to declare content types.
By default I implemented Markdown with CommonMark, but I think it's exactly at this place that you can add a configuration to enable ParseDown instead of CommonMark.

You can also add new content types via processors. (I already use it on a project at work to render mustache templates)

**Comment by holodyn** [comment]
This works - here are my thoughts for both the Markdown and refactoring discussion:

1. Several of the `Format\Base` files are still classes while others are abstract.  Ideally these would all be abstract.
2. CommonMark is being cast into the `Markdown` namespace in all three of the Formats, and is still referenced in the `Processor`.

If we were truly isolating the handlers then I would expect all handler (ContentType) logic to be isolated to a single folder.  Ideally all CommonMark objects and references (outside of a configuration directive) would be in a single folder for the system, with all format handlers contained within, for instance:

````
libs\Handler\Mustache\
libs\Handler\Mustache\HTML\
llibs\Handler\Parsedown\
libs\Handler\Parsedown\HTML\
libs\Handler\CommonMark\
libs\Handler\CommonMark\HTML\
````

**Comment by onigoetz** [comment]
I completely agree on the first point, this is true all these classes should be abstracts or interfaces.

Yes, CommonMark is being cast in the Processor for a very simple reason : each of these conversion systems have their own way to be extended. It seems very weird to me to create a method in the processor named something like `extendConversionHandler` and one time you get a ComonMark environment, and the next time you get a Mustache Engine.

But why not have another method in the processor for `extendParsedown` ?

Yes, the handlers can also be in a separated folder.

**Comment by holodyn** [comment]
I hear you.  It may be unreasonable to have a common extender, but it would be nice so that the processor doesn't have to change every time a new handler is added.

````
libs/Processor
class Processor {
	public function extendHandler( $handler ){
		$handlerClass = 'extendHandler' . $this->daux->options->handler;
		if( method_exists($this, $handlerClass) ){
			return call_user_func([$this, $handlerClass]);
		}
	}
}
````

````
libs/Extension/MyProcessor.php
class MyProcessor extends Processor {
	public function extendHandlerCommonMark( $handler ){
	}
}
````

**Comment by holodyn** [comment]
@onigoetz 

You removed the LOCAL_BASE declaration but in your notes generally mentioned that all issues were resolved.

What is the method for overloading the $daux->local_base?  I do not see an approach for this implemented.

**Pull request closed without merging**
