### PR TITLE
Directory level config.  Directory level IP request filter.

### PR DESCRIPTION
**Pull request by holodyn**
Added directory level config.json processing for ignore and filter rules.

The purpose for this is to allow the "ignore" and new "filter" rules to be defined within a directory.  This allows for a directory to contain previously allowed files / folders that are then ignored by the specific rules.  This also allows for directory level filters to be applied for limiting request access.

Added ip request filtering (config key filter.ips).

The purpose of this filter is to restrict access to a folder by remote ip address.  This filter is evaluated during the tree build and prevents the node from being added to the tree object entirely.

```json
	{
		"filter": {
			"ips": ["192.168.1.1"]
		}
	}
```

### CODE REVIEW

**Comment by onigoetz** [comment]
I gave this a thought and I might have an idea to make this solution more generic. 

First, I would separate this in two features/Pull requests : 
- Directory level configuration handling
- IP Filtering

## Directory level configuration handling
This one could be handled in two different ways, the first and most obvious one is to read a `config.json` file in the folder in question. as you did.

I thought of the second one when I was trying to figure out how to store the configuration to a folder in the configuration without cloning it (cloning the configuration is dangerous as I use the fact the object is shared across the whole application to propagate configuration changes; like theme rebase on generation) We could simply have this configuration in `config.json` at the root of the documentation:

```json
{
 "directory": {
    "More_Examples": {
      "ip_filter": "127.0.0.1"
    },
   "More_Examples/subdirectory": {
      "ip_filter": "192.168.1.1"
   }
 }
} 
```

Both ways to configure would be complementary to each other, and the configuration would be retrieved by a call to `getLocalConfiguration()` on a `Directory` instance.

What do you think about that ?

## IP Filtering
I think this feature is pretty much an edge case, I'm not sure a lot of people will use that feature.

That said, if you're willing to add it and will use it, I see no reason to refuse it.

What I propose you is to implement it as a Processor, by adding a hook on all directory creations.

What do you think ?

**Comment by holodyn** [comment]
I appreciate you thinking this through, and I always prefer the generic solution.  These are certainly two unique topics that merit their own consideration.

## Directory Level Configuration

I agree that cloning the configuration can lead to serious complications, and your solution does solve that problem.  

The scenario in which we found the inheritance useful was when using the software to display documents from multiple sources.  We have a separate repository for each document package, and have mapped them into a single docs folder to work with the app logic.  We prefer that each repository stay compartmentalized.  Without having some mechanism for configuration inheritance, we are forced to translate changes from each repository into the single configuration.  This can obviously lead to integrity issues.

Your solution for name spacing the directory specific configuration values is wonderful.  I can imagine how that can be expanded with future values, like entry specific theme or route options, while maintaining separation from core system values.  

To achieve this we can adjust your assertion that config.json be found only in the root folder, and merge the two concepts to allow subsequent config.json files to be parsed within a directory node, but inherit those values into the "directory" portion of the configuration object.  We can rename "directory" to "entry" so that the logic can translate to any node.  We could go a step further and allow import to include a "entry" array that is merged with the existing, allowing a single config.json file for a repo to control all subsequent content.

```` 
/config.json
{
  ... main values ...
  "entry": {
    "PackageA": {
      "ip_filter": "127.0.0.1"
    }
  }
}
````

```` 
/PackageA/config.json
{
  "ip_filter": "50.0.0.10"
  "entry": {
    "Introduction": {
      "ip_filter": "192.168.1.1"
    }
  }
}
````

```` 
** resulting configuration **
{
  ... main values ...
  "entry": {
    "PackageA": {
      "ip_filter": [ "127.0.0.1", "50.0.0.10" ]
    }
    "PackageA/Introduction": {
      "ip_filter": "127.0.0.1"
    }
  }
}
````

Value precedence would still be an issue and may be relegated to the type of value and definition.  In the preceding example, the original value of `entry.PackageA.ip_filter` is appended to contain both values.  Precedence could be simply a hard merge or overwrite rule.  The merge option could be the safest option, and for cases where a single value is needed the last in the stack is assumed.  Thinking out loud...

There are I'm sure other considerations to be made here, but I believe this approach can provide a safe convention for node specific arguments that can be defined at any level of the tree. 

Thoughts?

## IP Filtering

We are already using it so yes it would be useful for us, but we could work from a fork if necessary.

Regarding placement, this would be nice to have isolated in the processor and hooked into the directory.  We would need to overload the `Daux\Tree\Directory` constructor to prevent `setParent` from being called. Alternatively we could parse the whole tree and then implement the filters within the routing or navigation display operations.  For simplicity though I think aborting during the build is our best option.

**Comment by onigoetz** [comment]
That's right, an entry could also have a configuration, I was thinking that this could be handled by markdown content metadata. but this works also.

**Comment by onigoetz** [comment]
I think this should go in a plugin once this is supported

**Pull request closed without merging**
